artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1JVUx8i09Ua3aDRSUupXusVhFfGZYJkCS/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/legal_case_document.zip
  unzip_dir: artifacts/data_ingestion
  jsonl_file: artifacts/data_ingestion/
  csv_file: artifacts/data_ingestion/


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/legal_data
  tokenizer_name: nsi319/legal-led-base-16384