artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1JVUx8i09Ua3aDRSUupXusVhFfGZYJkCS/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/legal_case_dataset.zip
  unzip_dir: artifacts/data_ingestion
