# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockyqna

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://docqna.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_85151a52ae6c41c2867ccdbd39400bc3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3ae04f88a371401e830456fb1eff75f8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: docqna.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_85151a52ae6c41c2867ccdbd39400bc3 }}/docqna:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockyqna'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_88800cb3e5af4c09a66486dd55675771 }}
        images: 'docqna.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_85151a52ae6c41c2867ccdbd39400bc3 }}/docqna:${{ github.sha }}'